"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { TracingBeam } from "@/components/ui/tracing-beam";
import { SocialDock } from "@/components/SocialDock";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Portfolio",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {children}

        <div className="fixed bottom-0 w-full z-50 bg-transparent ">
          <SocialDock />
        </div>
      </body>
    </html>
  );
}
