"use client";
import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import { TracingBeam } from "@/components/ui/tracing-beam";
import { SocialDock } from "@/components/SocialDock";
import { Inter, Calistoga } from "next/font/google";
import { Variable } from "lucide-react";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const calistoga = Calistoga({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: "400",
});

// export const metadata: Metadata = {
//   title: "Portfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={twMerge(inter.variable, calistoga.variable,"bg-gray-900 text-white antialiased font-sans")}>
        {children}

        <div className="fixed bottom-0 w-full z-50 bg-transparent ">
          <SocialDock />
        </div>
      </body>
    </html>
  );
}
